hostel/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

from hostel.common.views import home, login_page, logout_page

urlpatterns = [

    # home
    path('', home, name="home"),

    # app: common
    path('autonomous_systems/', include('hostel.common.urls_autonomous_systems')),
    path('bundles/', include('hostel.common.urls_bundles')),
    path('cities/', include('hostel.common.urls_cities')),
    path('datacenters/', include('hostel.common.urls_datacenters')),
    path('groups/', include('hostel.common.urls_groups')),
    path('leases/', include('hostel.common.urls_leases')),
    path('users/', include('hostel.common.urls_users')),
    path('profile/', include('hostel.common.urls_profile')),
    path('service/', include('hostel.common.urls_services')),
    path('archived_services/', include('hostel.common.urls_archived_services')),
    path('staff/', include('hostel.common.urls_staff')),
    path('cc/', include('hostel.common.urls_cc')),

    path('clients/', include('hostel.clients.urls')),
    path('companies/', include('hostel.companies.urls')),
    path('devices/', include('hostel.devices.urls')),
    path('vlans/', include('hostel.vlans.urls')),
    path('nets/', include('hostel.nets.urls')),
    path('ins/', include('hostel.ins.urls')),
    path('store/', include('hostel.store.urls')),
    path('docs/', include('hostel.docs.urls')),
    path('search/', include('hostel.search.urls')),
    path('spy/', include('hostel.spy.spy_urls')),
    path('path_finder/', include('hostel.path_finder.urls')),
    path('map/', include('hostel.common.map_urls')),
    path('racks/', include('hostel.common.urls_racks')),

    # app: api
    path('api/', include('hostel.api.urls')),

    # authentication
    path('login/', login_page, name='login'),
    path('logout/', logout_page, name='logout'),

]

if 'django.contrib.staticfiles' in settings.INSTALLED_APPS and settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

hostel/common/forms.py
from django import forms
from django.contrib.auth.models import Group, Permission, User

from hostel.clients.models import Client
from hostel.devices.models import Device
from hostel.service.variables import lease_types
from datetime import datetime
from .models import (Service, SubService, Autonomoussystem, User,
                     Datacenter, Lease, City, BurstSet, LeaseGroup,
                     Ourservice, Phone, Rack, Photo)

ATTRS = {'class': 'form-control'}


class ClientFilterForm(forms.Form):
    select_row_height = 18

    # Services
    service_choices = [('', '')]
    height = len(service_choices) * select_row_height
    services = forms.MultipleChoiceField(choices=service_choices,
                                         widget=forms.SelectMultiple(attrs={'class': 'form-control',
                                                                            'style': 'height: %spx' % height}))

    # Cities
    cities_choices = [('', '')]
    height = len(cities_choices) * select_row_height
    cities = forms.MultipleChoiceField(choices=cities_choices,
                                       widget=forms.SelectMultiple(attrs={'class': 'form-control',
                                                                          'style': 'height: %spx' % height}))


class BundleVlanForm(forms.Form):
    device = forms.ModelChoiceField(required=True,
                                    queryset=Device.objects.all().order_by('netname'),
                                    widget=forms.Select(attrs={'class': 'form-control'}))
    bundle = forms.IntegerField(required=True,
                                widget=forms.TextInput(attrs={'class': 'form-control'}))


class ProvisionPeeringForm(forms.Form):
    device = forms.ModelChoiceField(required=True,
                                    queryset=Device.objects.all().order_by('netname'),
                                    widget=forms.Select(attrs={'class': 'form-control'}))
    bundle = forms.CharField(required=True,
                             widget=forms.TextInput(attrs={'class': 'form-control'}))


class BurstSetForm(forms.ModelForm):
    attrs = {'class': 'form-control'}
    name = forms.CharField(required=True, widget=forms.TextInput(attrs=attrs))
    client = forms.ModelChoiceField(required=True,
                                    queryset=Client.objects.filter(enabled=True, is_consumer=True),
                                    widget=forms.Select(attrs=attrs))
    limit = forms.IntegerField(required=False, widget=forms.NumberInput(attrs=attrs))
    price = forms.FloatField(required=True, widget=forms.TextInput(attrs=attrs))
    subscription_fee = forms.IntegerField(required=True, widget=forms.TextInput(attrs=attrs))
    with_tax = forms.BooleanField(required=False, widget=forms.CheckboxInput())
    direction = forms.ChoiceField(required=True, choices=BurstSet.DIRECTIONS, widget=forms.Select(attrs=attrs))

    class Meta:
        model = BurstSet
        fields = ['name', 'client', 'limit', 'price', 'with_tax', 'direction', 'subscription_fee']


class DateRangeForm(forms.Form):
    attrs = {'class': 'form-control'}
    format = '%Y-%m-%d'

    start_date = forms.DateField(required=True, input_formats=[format], widget=forms.DateInput(attrs=attrs))
    end_date = forms.DateField(required=True, input_formats=[format], widget=forms.DateInput(attrs=attrs))

    def __init__(self, *args, **kwargs):
        super(DateRangeForm, self).__init__(*args, **kwargs)

        today = datetime.now()

        start_month = today.month - 1
        start_year = today.year
        if start_month < 1:
            start_month = 12
            start_year -= 1

        start_time = today.replace(day=1, month=start_month, year=start_year)
        end_time = today.replace(day=1)

        start_date = start_time.date()
        end_date = end_time.date()

        self.initial['start_date'] = start_date
        self.initial['end_date'] = end_date


class BurstCalculationForm(DateRangeForm):
    pass


class ServiceForm(forms.ModelForm):
    attrs = {'class': 'form-control'}
    servicetype = forms.ChoiceField(required=True, widget=forms.Select(attrs=attrs))
    status = forms.ChoiceField(required=True, choices=Service.STATUSES, widget=forms.Select(attrs=attrs))
    cities = forms.ModelMultipleChoiceField(
        required=True,
        queryset=City.objects.all().order_by('name'),
        widget=forms.SelectMultiple(attrs=attrs)
    )
    asn = forms.ModelChoiceField(
        required=False,
        queryset=Autonomoussystem.objects.none(),
        widget=forms.Select(attrs=attrs)
    )
    start_time = forms.DateTimeField(required=True, widget=forms.DateTimeInput(attrs=attrs))
    end_time = forms.DateTimeField(required=True, widget=forms.DateTimeInput(attrs=attrs))
    rt = forms.CharField(required=False, widget=forms.TextInput(attrs=attrs))
    comment = forms.CharField(required=False, widget=forms.Textarea(attrs=attrs))
    description = forms.CharField(required=False, widget=forms.Textarea(attrs=attrs))
    commited_bandwidth = forms.IntegerField(required=False, widget=forms.NumberInput(attrs=attrs))
    maximum_bandwidth = forms.IntegerField(required=False, widget=forms.NumberInput(attrs=attrs))

    class Meta:
        model = Service
        fields = ['comment', 'description', 'servicetype', 'rt',
                  'status', 'start_time', 'end_time', 'cities', 'asn',
                  'commited_bandwidth', 'maximum_bandwidth']

    def __init__(self, *args, **kwargs):
        try:
            service_name = kwargs.pop('service_name')
            client = kwargs.pop('client')
            asn = kwargs.pop('asn')
        except KeyError:
            service_name = None
            client = None
            asn = None
        super(ServiceForm, self).__init__(*args, **kwargs)

        if not self.instance.pk:
            if not service_name or not client:
                raise ValueError('service_name and client are required')
            self.instance.name = service_name
            self.instance.client = client

        params = self.instance.params()
        if 'service_types' in params:
            self.fields['servicetype'].choices = params['service_types']

        if 'status' in params:
            self.fields['status'].initial = params['status']

        if 'require_as' in params:
            if params['require_as']:
                self.fields['asn'].required = True
                if self.instance.pk:
                    self.fields['asn'].queryset = Autonomoussystem.objects.filter(
                        client=self.instance.client).order_by('asn')
                else:
                    self.fields['asn'].queryset = Autonomoussystem.objects.filter(
                        client=client).order_by('asn')

    def validate_asn(self):
        asn = self.cleaned_data['asn']
        params = self.instance.params()
        if not params['require_as'] and asn:
            raise forms.ValidationError('Данный сервис не требует автономной системы')
        if params['require_as'] and not asn:
            raise forms.ValidationError('Данный сервис требует автономную систему')


class SubServiceForm(forms.ModelForm):
    attrs = {'class': 'form-control', 'autocomplete': 'off'}
    area_attrs = {'class': 'form-control', 'rows': 4}

    sub_id = forms.CharField(required=True, widget=forms.TextInput(attrs=attrs))
    rt = forms.CharField(required=False, widget=forms.TextInput(attrs=attrs))
    status = forms.ChoiceField(
        required=True,
        choices=SubService.STATUSES,
        widget=forms.Select(attrs=attrs))
    cities = forms.ModelMultipleChoiceField(
        queryset=City.objects.all().order_by('name'),
        required=True,
        widget=forms.SelectMultiple(attrs=attrs)
    )
    description = forms.CharField(required=False, widget=forms.Textarea(attrs=area_attrs))
    comment = forms.CharField(required=False, widget=forms.Textarea(attrs=area_attrs))

    class Meta:
        model = SubService
        fields = ['sub_id', 'comment', 'description', 'ticket', 'status', 'cities']

    def __init__(self, *args, **kwargs):
        service = None
        if 'service' in kwargs:
            service = kwargs.pop('service')

        super().__init__(*args, **kwargs)
        self.service = service
        if self.service:
            self.initial['ticket'] = self.service.ticket
            self.initial['description'] = self.service.description
            self.initial['cities'] = self.service.cities.all()

    def clean_sub_id(self):
        sub_id = self.cleaned_data['sub_id']
        if not self.instance.pk:
            # check if we have such subservice
            if SubService.objects.filter(service=self.service, sub_id=sub_id).count() > 0:
                raise forms.ValidationError('ID назначен другой подуслуге %s' % self.service)

        return sub_id

    def save(self, *args, **kwargs):
        if not self.instance.pk:
            self.instance.service = self.service
        return super().save(*args, **kwargs)


class ServicesFilterForm(forms.Form):
    attrs = {'class': 'form-control'}

    NAME_CHOICES = (
        ('', '')
    )
    name = forms.MultipleChoiceField(required=False, choices=NAME_CHOICES, widget=forms.SelectMultiple(attrs=attrs))
    service_type = forms.CharField(required=False, widget=forms.TextInput(attrs=attrs))
    text = forms.CharField(required=False, widget=forms.TextInput(attrs=attrs))
    status = forms.MultipleChoiceField(required=False, choices=Service.STATUSES,
                                       widget=forms.SelectMultiple(attrs=attrs))
    manager = forms.ModelChoiceField(
        required=False,
        queryset=User.objects.filter(is_active=True),
        widget=forms.Select(attrs=attrs)
    )
    DOC_CHOICES = (
        (None, 'Не важно'),
        ('yes', 'Да'),
        ('no', 'Нет'),
    )
    has_document = forms.ChoiceField(required=False, choices=DOC_CHOICES, widget=forms.Select(attrs=attrs))

hostel/common/templates/bs3/lease/application_block.html
<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title">Заказ</h3>
    </div>

    <table class="table">

        {% if lease.application %}
            <tr>
                <td>
                    {% with lease.application as application %}
                        {% if application.filename %}
                            <span class="glyphicon glyphicon-file text-success" aria-hidden="true"></span>
                        {% else %}
                            <span class="glyphicon glyphicon-file text-danger" aria-hidden="true"></span>
                        {% endif %}
                        <a href="{% url 'application' application.pk %}" title="{{ application }}">{{ application|truncatechars:36 }}</a>
                    {% endwith %}
                </td>

                <td class="text-right">
                    <button class="btn btn-xs btn-warning" data-toggle="modal" data-target=".bs-example-modal-sm">
                        <span class="glyphicon glyphicon-trash"></span>
                    </button>
                </td>
            </tr>
        {% else %}
            <tr>
                <td class="text-center">
                    <a href="{% url 'choose_doc_for_lease' lease.pk %}">Выбрать документ</a>
                </td>
            </tr>
        {% endif %}

    </table>

</div>

<div class="modal fade bs-example-modal-sm" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel">
    <div class="modal-dialog modal-md" role="document">
        <div class="modal-content">

            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Отвязать документ?</h4>
            </div>

            <div class="modal-body">
                <p>Вы собираетесь отвязать документ «{{ lease.application|truncatechars:20 }}» от лизы</p>
            </div>

            <div class="modal-footer">
                <form method="POST">
                    {% csrf_token %}
                    <button type="button" class="btn btn-default" data-dismiss="modal">Я еще подумаю...</button>
                    <button type="submit" name="action" value="release_application" class="btn btn-warning">Отвязать</button>
                </form>
            </div>

        </div>
    </div>
</div>

hostel/common/templates/bs3/lease/delete_lease_group_button.html
<a class="btn btn-danger" data-toggle="modal" data-target="#delete_lease">
    <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
</a>

<div class="modal fade text-left" id="delete_lease" tabindex="-1" role="dialog">
    <form method="POST">
        {% csrf_token %}

        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                            aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="myModalLabel">Удалить группу?</h4>
                </div>
                <div class="modal-body">

                    <p>Вы собираетесь удалить следующую группу лиз:</p>

                    <p><div class="color-marker color-leasegroup"></div>
                    <b>{{ lease_group.description }}</b></p>

                    <p>Действие необратимо</p>

                    <input type="hidden" name="id" value="{{ lease_group.pk }}">


                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Я еще подумаю...</button>
                    <button type="submit" class="btn btn-danger" name="action" value="delete_lease_group">Удалить</button>
                </div>
            </div>
        </div>
    </form>
</div>

hostel/common/templates/bs3/lease/disturb_provider.html
<a class="btn btn-primary" data-toggle="modal" data-target="#disturb_provider">
    <span class="glyphicon glyphicon-envelope" aria-hidden="true"></span> Написать поставщику
</a>

<div class="modal fade text-left" id="disturb_provider" tabindex="-1" role="dialog">
    <form method="POST">
        {% csrf_token %}

        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                            aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="myModalLabel">Создание тикета RT и обращения к поставщику</h4>
                </div>
                <div class="modal-body">

                    <div class="form-group">
                        <label for="id_subject">Тема сообщения</label>
                        <input class="form-control" name="subject" id="id_subject" value="{{ lease.identity }}{% if lease.addresses %} {{ lease.addresses }}{% endif %}">
                    </div>

                    <div class="form-group">
                        <label for="id_support_email">Support Email</label>
                        <input class="form-control" name="support_email" id="id_support_email" value="{{ lease.get_support_email|default:'' }}">
                    </div>

                    <div class="form-group">
                        <label for="id_message">Текст сообщения</label>

                        <textarea class="form-control" name="message" id="id_message" rows="10">Коллеги,
Мы берем у вас следующую услугу:
{% if lease.identity %}{{ lease.identity }}{% endif %} {% if lease.addresses %}{{ lease.addresses }}{% endif %}
{% if lease.agreement %}{{ lease.agreement }}{% endif %}
Фиксируем проблему по услуге:

Просим провести диагностику с вашей стороны.
Заранее спасибо!

{{ request.user.get_full_name }}
</textarea>
                        <div class="help-block">Если оставить поле пустым, будет создан тикет без сообщения.</div>
                    </div>


                    <div class="form-group">
                        <label>Родительский #RT</label>
                        <input class="form-control" type="text" name="parent_rt">
                    </div>

                    <div class="form-group">
                        <label class="control-label" for="id_report_ticket">
                            <input type="checkbox" id="id_report_ticket" name="report_client_check">
                            Отписать клиенту о создании тикета
                        </label>

                    </div>


                    <div class="form-group" id="report_text_block">

                        <textarea class="form-control" rows="5" id="id_report_text" name="report_text">Сдали проблему на проверку подрядчику.
По результатам отпишем.

{{ request.user.first_name }} {{ request.user.last_name }}</textarea>
                    </div>

                </div>

                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Отмена</button>
                    <button type="submit" class="btn btn-primary" name="action" value="disturb_provider">
                        <span class="glyphicon glyphicon-envelope" aria-hidden="true"></span> Написать поставщику
                    </button>
                </div>
            </div>
        </div>
    </form>
</div>
<script>

    $('#report_text_block').slideUp();

    $('#id_report_ticket').change(function () {
        if (this.checked) {
            $('#report_text_block').slideDown();
        } else {
            $('#report_text_block').slideUp();
        }
    })
</script>

hostel/common/templates/bs3/lease/filter_form.html
<div class="form-group {% if filter_form.types.errors %}has-error{% endif %}">
    <label>Тип</label><br>
    {% if filter_form.types.errors %}
    {{ filter_form.types.errors }}
    {% endif %}
    {{ filter_form.types }}
</div>

<div class="form-group {% if filter_form.cities.errors %}has-error{% endif %}">
    <label>Содержит города</label><br>
    {% if filter_form.cities.errors %}
        {{ filter_form.cities.errors }}
    {% endif %}
    {{ filter_form.cities }}
</div>
<div class="form-group {% if filter_form.provider.errors %}has-error{% endif %}">
    <label>Поставщик</label><br>
    {% if filter_form.provider.errors %}
        {{ filter_form.provider.errors }}
    {% endif %}
    {{ filter_form.provider }}
</div>
<div class="form-group {% if filter_form.is_ours.errors %}has-error{% endif %}">
    <label>Для нас</label><br>
    {% if filter_form.is_ours.errors %}
        {{ filter_form.is_ours.errors }}
    {% endif %}
    {{ filter_form.is_ours }}
</div>
<div class="form-group {% if filter_form.is_bought.errors %}has-error{% endif %}">
    <label>Выкуплен</label><br>
    {% if filter_form.is_bought.errors %}
        {{ filter_form.is_bought.errors }}
    {% endif %}
    {{ filter_form.is_bought }}
</div>
<div class="form-group {% if filter_form.search_string.errors %}has-error{% endif %}">
    <label>Ключевые слова</label><br>
    {% if filter_form.search_string.errors %}
        {{ filter_form.search_string.errors }}
    {% endif %}
    {{ filter_form.search_string }}
</div>
<div class="form-group">
    <label>&nbsp;</label><br>
    <button type="submit" class="btn btn-primary form-control">
        <span class="glyphicon glyphicon-filter"></span>
        {{ leases.count|default:0 }}
    </button>
</div>
<div class="form-group">
    <label>&nbsp;</label><br>
    <a href="{% url 'leases' %}" class="btn btn-default form-control">
        <span class="glyphicon glyphicon-erase"></span>
    </a>
</div>

<script>
    $('#id_types').select2({width: 200});
    $('#id_cities').select2({width: 200});
    $('#id_provider').select2({width: 200});
    $('#id_search_string').focus();
</script>

hostel/common/templates/bs3/lease/group_create.html
{% extends 'bs3/base.html' %}
{% block title %}*Создать lease{% endblock %}
{% block content %}

    {% include 'bs3/lease/leases_tabs.html' %}

    <div class="container">

        <br>

        <!-- Заголовок, кнопка редактирования -->
        <div class="row" style="margin-bottom: 16px;">
            <div class="col-md-8">
                <h4>
                    <div class="color-marker color-leasegroup"></div>
                    Создание группы лиз
                </h4>
            </div>
            <div class="col-md-4 text-right">
                <button type="submit" form="lease_group_data" class="btn btn-primary">Создать</button>
            </div>
        </div>

        <!-- Колонка с общими данными клиента -->
        <div class="row">


            <div class="col-md-2">
            </div>


            <div class="col-md-8">


                <!-- Данные клиента -->
                <form id="lease_group_data" METHOD="POST">
                    {% csrf_token %}
                    {% include 'bs3/lease/lease_group_form.html' %}
                </form>


            </div>

            <div class="col-md-2">
            </div>

        </div>
    </div>

{% endblock %}

hostel/common/templates/bs3/lease/group_list.html
{% extends 'bs3/base.html' %}
{% load hostel_filters %}
{% block title %}Leases{% endblock %}
{% block content %}

    <div class="container-fluid">
        <ol class="breadcrumb">
            <li><a href="{% url 'home' %}"><span class="glyphicon glyphicon-home" aria-hidden="true"></span></a></li>
            <li><a href="{% url 'leases' %}">Лизы</a></li>
            <li class="active">Группы</li>
        </ol>
    </div>

    <div class="container-fluid text-right">
    <a class="btn btn-primary" href="{% url 'create_lease_group' %}">
        <span class="glyphicon glyphicon-plus"></span> Создать
    </a>
    </div>

    <table class="table">

        <thead>
        <tr>
            <th>#</th>
            <th>Группа</th>
            <th>RT#</th>
            <th>Лизы</th>
        </tr>
        </thead>

        <tbody>
        {% for lease_group in lease_groups %}
            <tr>
                <td class="text-muted">{{ lease_group.pk }}</td>
                <td class="active">
                    <a href="{% url 'lease_group' lease_group.pk %}">
                        <div class="color-marker color-leasegroup"></div>
                        <b>{{ lease_group.description }}</b>
                    </a>
                </td>
                <td>{{ lease_group.rt|ticket }}</td>
                <td class="text-muted">
                    {% for lease in lease_group.leases.all %}
                        <div class="color-marker color-lease"></div>
                            <b><a href="{% url 'lease' lease.pk %}">{{ lease }}</a></b>
                            <small>{{ lease.identity }}</small><br>
                    {% endfor %}
                </td>
            </tr>
        {% empty %}
            <tr>
                <td colspan="4" class="text-muted text-center">Пусто</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>


{% endblock %}

hostel/common/templates/bs3/lease/group_view.html
{% extends 'bs3/base.html' %}
{% block title %}Lease {{ lease }}{% endblock %}
{% block content %}

    <div class="container">

        <ol class="breadcrumb">
            <li><a href="{% url 'home' %}"><span class="glyphicon glyphicon-home" aria-hidden="true"></span></a></li>
            <li><a href="{% url 'leases' %}">Лизы</a></li>
            <li><a href="{% url 'lease_groups' %}">Группы</a></li>
            <li class="active">{{ lease_group }}</li>
        </ol>

        <!-- Заголовок, кнопка редактирования -->
        <div class="row" style="margin-bottom: 16px;">
            <div class="col-md-8">
                <h4>
                    <div class="color-marker color-leasegroup"></div>
                    {{ lease_group }}
                </h4>
            </div>
            <div class="col-md-4 text-right">
                {% if mode == 'edit' %}
                    <a class="btn btn-default" href="{% url 'lease_group' lease_group.pk %}">Отмена</a>
                    <button type="submit" form="lease_group_form" class="btn btn-primary">Сохранить</button>
                {% else %}
                    {% if perms.common.change_lease %}
                        <a class="btn btn-primary" href="{% url 'update_lease_group' lease_group.pk %}"><span class="glyphicon glyphicon-edit"></span> Редактировать</a>
                    {% endif %}
                {% endif %}
            </div>
        </div>


        <div class="row">

            <div class="col-md-4">

                {% if mode == "edit" %}
                    <form method="POST" id="lease_group_form">
                        {% csrf_token %}
                        <input type="hidden" name="id" placeholder="lease_id" value="{{ lease.pk }}">
                        {% include 'bs3/lease/lease_group_form.html' %}
                    </form>
                {% else %}
                    {% include 'bs3/lease/lease_group_data.html' %}
                {% endif %}

                {% with lease_group as object %}
                    {% include 'bs3/common/created_updated.html' %}
                {% endwith %}

            </div>

            <div class="col-md-8">

                {% with lease_group.leases.all as leases %}

                    {% include 'bs3/lease/leases_panel.html' %}

                {% endwith %}

            </div>


        </div>

        {% if mode == 'view' %}

            <div class="well text-right">

                {% if perms.common.delete_lease %}
                    {% include 'bs3/lease/delete_lease_group_button.html' %}
                {% endif %}

            </div>

        {% endif %}

    </div>

    {% include 'bs3/spy/object_log.html' %}

{% endblock %}

hostel/common/templates/bs3/lease/lease_form.html
<div class="form-group {% if form.type.errors %}has-error{% endif %}">
    <label class="control-label">Тип</label>
    {{ form.type }}
    {% for error in form.type.errors %}
        <span class="text-danger">{{ error }}</span>
    {% endfor %}
</div>

<div class="form-group {% if form.organization.errors %}has-error{% endif %}">
    <label class="control-label">Подрядчик</label><br>
    {{ form.organization }}
    {% for error in form.organization.errors %}
        <span class="text-danger">{{ error }}</span>
    {% endfor %}
</div>

<div class="form-group {% if form.ticket.errors %}has-error{% endif %}">
    <label class="control-label">Тикет</label>
    {{ form.ticket }}
    {% for error in form.ticket.errors %}
        <span class="text-danger">{{ error }}</span>
    {% endfor %}
</div>

<div class="form-group {% if form.cities.errors %}has-error{% endif %}">
    <label class="control-label">Города</label>
    {{ form.cities }}
    {% for error in form.cities.errors %}
        <span class="text-danger">{{ error }}</span>
    {% endfor %}
</div>

<div class="checkbox">
    <label>{{ form.is_ours }} <b>Для нас</b></label>
    <span class="help-block">Услуга для нас: магистрали, оптика, каналы</span>
</div>

<div class="checkbox">
    <label>{{ form.is_bought }} <b>Волокно выкуплено</b></label>
</div>


<div class="form-group {% if form.google_map_url.errors %}has-error{% endif %}">
<label>Google Map URL</label>
    {% if form.google_map_url.errors %}
    {{ form.google_map_url.errors }}
    {% endif %}
    {{ form.google_map_url }}
    <span class="help-block">Схема карты в Google Maps</span>

</div>

<div class="form-group {% if form.agreement.errors %}has-error{% endif %}">
    <label class="control-label">Договор, заказ</label>
    {{ form.agreement }}
    {% for error in form.agreement.errors %}
        <span class="text-danger">{{ error }}</span>
    {% endfor %}
</div>

<div class="form-group {% if form.identity.errors %}has-error{% endif %}">
    <label class="control-label">Идентификация или Service ID</label>
    {{ form.identity }}
    {% for error in form.identity.errors %}
        <span class="text-danger">{{ error }}</span>
    {% endfor %}
    <span class="help-block">Идентификация, понятная подрядчику</span>

</div>

<div class="form-group {% if form.addresses.errors %}has-error{% endif %}">
    <label class="control-label">Адреса включения</label>
    {{ form.addresses }}
    {% for error in form.addresses.errors %}
        <span class="text-danger">{{ error }}</span>
    {% endfor %}
    <span class="help-block">Если применимо</span>

</div>

<div class="form-group {% if form.group.errors %}has-error{% endif %}">
    <label class="control-label">Группа</label><br>
    {{ form.group }}
    {% for error in form.group.errors %}
        <span class="text-danger">{{ error }}</span>
    {% endfor %}
</div>

<div class="form-group {% if form.support_email.errors %}has-error{% endif %}">
    <label>Support Email</label>
    <span class="text-danger">{{ form.support_email.errors }}</span>
    {{ form.support_email }}
    <div class="help-block">Если отличается от Support Email подрядчика</div>
</div>

<div class="form-group {% if form.contacts.errors %}has-error{% endif %}">
    <label>Support контакты</label>
    {{ form.contacts.errors }}
    {{ form.contacts }}
    <div class="help-block">Если отличается от Support-контактов подрядчика</div>
</div>

<div class="form-group {% if form.comment.errors %}has-error{% endif %}">
    <label>Комментарии</label>
    {{ form.comment.errors }}
    {{ form.comment }}
</div>

<script>
$(document).ready(function() {
    $("#id_organization").select2();
    $("#id_cities").select2();
    $("#id_group").select2();
})
</script>