hostel/clients/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.client_list, name='clients'),
    path('netname/<netname>', views.client_netname_view, name='client_netname'),
    path('<int:client_id>/', views.client_view, name='client'),
    path('<int:client_id>/update/', views.client_update, name='update_client'),
    path('<int:client_id>/export_services/', views.export_services, name='export_services'),
    path('<int:client_id>/request_service/', views.request_service, name='request_service'),
    path('add/', views.client_create, name='add_client'),
    path('delete/', views.client_delete, name='delete_client'),
]

hostel/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

from hostel.common.views import home, login_page, logout_page

urlpatterns = [

    # home
    path('', home, name="home"),

    # app: common
    path('autonomous_systems/', include('hostel.common.urls_autonomous_systems')),
    path('bundles/', include('hostel.common.urls_bundles')),
    path('cities/', include('hostel.common.urls_cities')),
    path('datacenters/', include('hostel.common.urls_datacenters')),
    path('groups/', include('hostel.common.urls_groups')),
    path('leases/', include('hostel.common.urls_leases')),
    path('users/', include('hostel.common.urls_users')),
    path('profile/', include('hostel.common.urls_profile')),
    path('service/', include('hostel.common.urls_services')),
    path('archived_services/', include('hostel.common.urls_archived_services')),
    path('staff/', include('hostel.common.urls_staff')),
    path('cc/', include('hostel.common.urls_cc')),

    path('clients/', include('hostel.clients.urls')),
    path('companies/', include('hostel.companies.urls')),
    path('devices/', include('hostel.devices.urls')),
    path('vlans/', include('hostel.vlans.urls')),
    path('nets/', include('hostel.nets.urls')),
    path('ins/', include('hostel.ins.urls')),
    path('store/', include('hostel.store.urls')),
    path('docs/', include('hostel.docs.urls')),
    path('search/', include('hostel.search.urls')),
    path('spy/', include('hostel.spy.spy_urls')),
    path('path_finder/', include('hostel.path_finder.urls')),
    path('map/', include('hostel.common.map_urls')),
    path('racks/', include('hostel.common.urls_racks')),

    # app: api
    path('api/', include('hostel.api.urls')),

    # authentication
    path('login/', login_page, name='login'),
    path('logout/', logout_page, name='logout'),

]

if 'django.contrib.staticfiles' in settings.INSTALLED_APPS and settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

hostel/clients/forms.py
from django import forms
from .models import Client
import hostel.common.models as common_models
from hostel.common.models import User
from django.core.exceptions import ValidationError


class ClientFilterForm(forms.Form):
    default_attrs = {'class': 'form-control'}

    netname = forms.CharField(required=False,
                              widget=forms.TextInput(attrs=default_attrs))

    cities = forms.ModelMultipleChoiceField(queryset=common_models.City.objects.all().order_by('name'),
                                            widget=forms.SelectMultiple(attrs=default_attrs),
                                            required=False)

    manager = forms.ModelMultipleChoiceField(queryset=User.objects.all().order_by('username'),
                                             widget=forms.SelectMultiple(attrs=default_attrs),
                                             required=False)

    search_string = forms.CharField(required=False, widget=forms.TextInput(attrs=default_attrs))

    statuses = (('', 'Любой'), ('+', '+'), ('-', '-'))
    status = forms.ChoiceField(required=False, choices=statuses, widget=forms.Select(attrs=default_attrs))


class ClientForm(forms.ModelForm):
    class Meta:
        model = Client
        fields = ['netname',
                  'clientname',
                  'engname',
                  'city',
                  'address',
                  'contacts',
                  'support_contacts',
                  'comment',
                  'email',
                  'support_email',
                  'url',
                  'manager',
                  'ticket',
                  'is_consumer',
                  'is_provider',
                  'enabled']

        widgets = {
            'netname': forms.TextInput(attrs={'class': 'form-control'}),
            'clientname': forms.TextInput(attrs={'class': 'form-control'}),
            'engname': forms.TextInput(attrs={'class': 'form-control'}),
            'city': forms.Select(attrs={'class': 'form-control'}),
            'address': forms.TextInput(attrs={'class': 'form-control'}),
            'contacts': forms.Textarea(attrs={'class': 'form-control', 'rows': '5'}),
            'support_contacts': forms.Textarea(attrs={'class': 'form-control', 'rows': '5'}),
            'comment': forms.Textarea(attrs={'class': 'form-control', 'rows': '4'}),
            'email': forms.TextInput(attrs={'class': 'form-control'}),
            'support_email': forms.TextInput(attrs={'class': 'form-control'}),
            'url': forms.TextInput(attrs={'class': 'form-control'}),
            'manager': forms.Select(attrs={'class': 'form-control'}),
            'ticket': forms.TextInput(attrs={'class': 'form-control'}),
            'is_consumer': forms.CheckboxInput(),
            'is_provider': forms.CheckboxInput(),
            'enabled': forms.CheckboxInput(),
        }


class RequestServiceForm(forms.Form):
    default_attrs = {'class': 'form-control'}
    parent_rt = forms.IntegerField(required=False, widget=forms.TextInput(attrs=default_attrs))
    ports = forms.CharField(required=True, widget=forms.TextInput(attrs=default_attrs))
    contacts = forms.CharField(required=True, widget=forms.Textarea(attrs=default_attrs))
    comment = forms.CharField(required=False, widget=forms.TextInput(attrs=default_attrs))

    def clean_ports(self):
        ports = str(self.cleaned_data['ports'])
        if '-r' not in ports and not '-sw' in ports:
            raise ValidationError('Порт должен содержать имя свитча или роутера. '
                                  'Например: rostov-sw1', code='wrong_ports')
        return ports

    def clean_contacts(self):
        if '@' not in self.cleaned_data['contacts']:
            raise ValidationError('В контактах должен быть email.', code='wrong_contacts')
        return self.cleaned_data['contacts']


class RequestServiceL2Form(RequestServiceForm):
    default_attrs = {'class': 'form-control'}
    addresses = forms.CharField(required=True, widget=forms.Textarea(attrs=default_attrs))
    service_type = forms.ChoiceField(widget=forms.Select(attrs=default_attrs),
                                     choices=common_models.service_l2.TYPES)


class RequestServiceBGPForm(RequestServiceForm):
    default_attrs = {'class': 'form-control'}
    inet2_requested = forms.BooleanField(required=False)
    wix_requested = forms.BooleanField(required=False)
    bgpinet_requested = forms.BooleanField(required=False)

    inet2_type = forms.ChoiceField(widget=forms.Select(attrs=default_attrs),
                                   choices=common_models.service_inet2.TYPES)

    wix_type = forms.ChoiceField(widget=forms.Select(attrs=default_attrs),
                                 choices=common_models.service_wix.TYPES)

    bgpinet_type = forms.ChoiceField(widget=forms.Select(attrs=default_attrs),
                                     choices=common_models.service_bgpinet.TYPES)

    mode_choices = (
        ('', ''),
        ('test', 'Тест'),
        ('commerce', 'Коммерция'),
    )
    mode = forms.ChoiceField(required=True, choices=mode_choices, widget=forms.Select(attrs=default_attrs))

    test_period = forms.IntegerField(required=False, min_value=1, max_value=30, initial=14,
                                     widget=forms.NumberInput(attrs=default_attrs))

    def clean(self):
        bgpinet_requested = self.cleaned_data['bgpinet_requested']
        wix_requested = self.cleaned_data['wix_requested']
        inet2_requested = self.cleaned_data['inet2_requested']
        if not bgpinet_requested and not inet2_requested and not wix_requested:
            raise ValidationError('Не выбрана услуга', code='no_service')

hostel/clients/templates/bs3/clients/request_service/bgp_form.html
<h3>Запрос на BGP-услуги</h3>

{% if form.non_field_errors %}
    <div class="text-danger">
        {% for error in form.non_field_errors %}
            <p class="form-error">{{ error }}</p>
        {% endfor %}
    </div>
{% endif %}

<div class="form-group {% if form.parent_rt.errors %}has-error{% endif %}">
    <label class="control-label">Родительская заявка RT</label>
    {{ form.parent_rt.errors }}
    {{ form.parent_rt }}
    <div class="help-block">Созданный тикет станет потомком</div>
</div>

<div class="form-group">

    <label class="control-label" for="id_inet2_requested">{{ form.inet2_requested }} Inet2</label><br>

    <div id="inet2_group">
        {{ form.inet2_type }}
    </div>
    <div class="help-block">BGP Full View по пиринговой схеме</div>

</div>

<div class="form-group">
    <label class="control-label" for="id_wix_requested">{{ form.wix_requested }} W-IX</label><br>

    <div id="wix_group">
        {{ form.wix_type }}
    </div>
    <div class="help-block">Международный пиринг</div>

</div>

<div class="form-group">
    <label class="control-label" for="id_bgpinet_requested">{{ form.bgpinet_requested }} BGP Inet</label>
    <div id="bgpinet_group">
        {{ form.bgpinet_type }}
    </div>
    <div class="help-block">Классический интернет по BGP</div>

</div>


<div class="form-group {% if form.ports.errors %}has-error{% endif %}">
    <label class="control-label">Порт/Порты включения</label>
    {{ form.ports.errors }}
    {{ form.ports }}
    <div class="help-block">Например: mrxst-sw0 port 2</div>
</div>

<div class="form-group {% if form.contacts.errors %}has-error{% endif %}">
    <label class="control-label">Контактные данные</label>
    {{ form.contacts.errors }}
    {{ form.contacts }}
    <div class="help-block">С кем взаимодействовать по согласованию и включению</div>
</div>

<div class="form-group {% if form.mode.errors %}has-error{% endif %}">
    <label class="control-label">Коммерция/тест?</label>
    {{ form.mode.errors }}
    {{ form.mode }}

    <div id="period_group">
        <label class="control-label">Период теста (дней)</label>
        {{ form.test_period.errors }}
        {{ form.test_period }}
    </div>

</div>

<div class="form-group {% if form.comment.errors %}has-error{% endif %}">
    <label class="control-label">Что бы вы хотели добавить от себя?</label>
    {{ form.comment.errors }}
    {{ form.comment }}
</div>

<script>

    $(document).ready(function () {
        show_groups();
    });

    $mode_select = $('#id_mode');

    function show_groups() {

        $inet2_requested = $("#id_inet2_requested");
        $wix_requested = $("#id_wix_requested");
        $bgpinet_requested = $("#id_bgpinet_requested");

        if ($inet2_requested.prop('checked')) {
            $('#inet2_group').slideDown();
        } else {
            $('#inet2_group').slideUp();

        }

        if ($wix_requested.prop('checked')) {
            $('#wix_group').slideDown();
        } else {
            $('#wix_group').slideUp();

        }

        if ($bgpinet_requested.prop('checked')) {
            $('#bgpinet_group').slideDown();
        } else {
            $('#bgpinet_group').slideUp();

        }

        if ($mode_select.val() == 'test') {
            $('#period_group').slideDown();
        } else {
            $('#period_group').slideUp();
        }


    }

    $('input[type=checkbox]').change(function () {
        show_groups();
    });

    $mode_select.change(function () {
        show_groups();
    })

</script>

hostel/clients/templates/bs3/clients/request_service/l2_form.html
<h3>Запрос на L2-канал</h3>

{% if form.non_field_errors %}
    <div class="text-danger">
        {% for error in form.non_field_errors %}
            <p class="form-error">{{ error }}</p>
        {% endfor %}
    </div>
{% endif %}

<div class="form-group {% if form.parent_rt.errors %}has-error{% endif %}">
    <label class="control-label">Родительская заявка RT</label>
    {{ form.parent_rt.errors }}
    {{ form.parent_rt }}
    <div class="help-block">Созданный тикет станет потомком</div>
</div>

<div class="form-group">
    <label class="control-label" for="id_service_type">Тип услуги</label>
    {{ form.service_type }}
</div>


<div class="form-group {% if form.ports.errors %}has-error{% endif %}">
    <label class="control-label">Порт/Порты включения</label>
    {{ form.ports.errors }}
    {{ form.ports }}
    <div class="help-block">Например: mrxst-sw0 port 2</div>
</div>

<div class="form-group {% if form.addresses.errors %}has-error{% endif %}">
    <label class="control-label">Точки включения (адреса)</label>
    {{ form.addresses.errors }}
    {{ form.addresses }}
    <div class="help-block">Например: Москва, Бутлерова, 7 - Нижегородская, 32</div>
</div>


<div class="form-group {% if form.contacts.errors %}has-error{% endif %}">
    <label class="control-label">Контактные данные</label>
    {{ form.contacts.errors }}
    {{ form.contacts }}
    <div class="help-block">С кем взаимодействовать по согласованию и включению</div>
</div>

<div class="form-group {% if form.comment.errors %}has-error{% endif %}">
    <label class="control-label">Что бы вы хотели добавить от себя?</label>
    {{ form.comment.errors }}
    {{ form.comment }}
</div>