hostel/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

from hostel.common.views import home, login_page, logout_page

urlpatterns = [

    # home
    path('', home, name="home"),

    # app: common
    path('autonomous_systems/', include('hostel.common.urls_autonomous_systems')),
    path('bundles/', include('hostel.common.urls_bundles')),
    path('cities/', include('hostel.common.urls_cities')),
    path('datacenters/', include('hostel.common.urls_datacenters')),
    path('groups/', include('hostel.common.urls_groups')),
    path('leases/', include('hostel.common.urls_leases')),
    path('users/', include('hostel.common.urls_users')),
    path('profile/', include('hostel.common.urls_profile')),
    path('service/', include('hostel.common.urls_services')),
    path('archived_services/', include('hostel.common.urls_archived_services')),
    path('staff/', include('hostel.common.urls_staff')),
    path('cc/', include('hostel.common.urls_cc')),

    path('clients/', include('hostel.clients.urls')),
    path('companies/', include('hostel.companies.urls')),
    path('devices/', include('hostel.devices.urls')),
    path('vlans/', include('hostel.vlans.urls')),
    path('nets/', include('hostel.nets.urls')),
    path('ins/', include('hostel.ins.urls')),
    path('store/', include('hostel.store.urls')),
    path('docs/', include('hostel.docs.urls')),
    path('search/', include('hostel.search.urls')),
    path('spy/', include('hostel.spy.spy_urls')),
    path('path_finder/', include('hostel.path_finder.urls')),
    path('map/', include('hostel.common.map_urls')),
    path('racks/', include('hostel.common.urls_racks')),

    # app: api
    path('api/', include('hostel.api.urls')),

    # authentication
    path('login/', login_page, name='login'),
    path('logout/', logout_page, name='logout'),

]

if 'django.contrib.staticfiles' in settings.INSTALLED_APPS and settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

hostel/common/models.py
import datetime
import json

import netaddr
from django.contrib.auth.models import AbstractBaseUser, UserManager, PermissionsMixin
from django.contrib.auth.validators import *
from django.db import models
from django.db.models import Q

from hostel.nets.models import Net, Netaggregator
from hostel.service.variables import lease_types, service_params, validate_mail_list, validate_netname
from hostel.settings import MEDIA_ROOT, STUPID_SHORTS
from hostel.vlans.models import Vlan
from hostel.vlans.models import Vlanaggregator


class User(AbstractBaseUser, PermissionsMixin):
    """
    Custom Hostel user
    """

    REQUIRED_FIELDS = ['email']

    THEMES = (
        ('bs3', 'BS3'),
    )
    GENDERS = (('male', 'Мужчина'), ('female', 'Женщина'))
    USER_KINDS = (
        ('tech', 'Технический персонал'),
        ('buh', 'Бухгалтерия'),
        ('manager', 'Менеджер'),
        ('project', 'Проект-менеджер')
    )

    username_validator = UnicodeUsernameValidator()

    username = models.CharField(max_length=40, unique=True, null=False, blank=False, validators=[username_validator])
    first_name = models.CharField(max_length=30, null=True, blank=True)
    last_name = models.CharField(max_length=30, null=True, blank=True)
    mid_name = models.CharField(max_length=30, null=True, blank=True)

    email = models.EmailField(null=True, blank=True, unique=True)
    phone = models.CharField(max_length=30, blank=True, null=True)
    ext_phone = models.CharField(max_length=30, blank=True, null=True)

    birthday = models.DateTimeField(blank=True, null=True, default=None)
    position = models.CharField(max_length=255, blank=True, null=True)

    kind = models.CharField(max_length=20, choices=USER_KINDS, null=False)
    gender = models.CharField(choices=GENDERS, max_length=20)
    theme = models.CharField(max_length=20, choices=THEMES, default=THEMES[0][0])
    pagination_count = models.PositiveIntegerField(blank=False, null=False, default=50)

    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    is_superuser = models.BooleanField(default=False)

    photo = models.ImageField(null=True, upload_to='user_photos')

    last_login = models.DateTimeField(null=True)
    date_joined = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    objects = UserManager()

    USERNAME_FIELD = 'username'

    class Meta:
        ordering = ['id']
        db_table = 'users'
        swappable = 'AUTH_USER_MODEL'

    def get_full_name(self):
        values = []
        if self.first_name:
            values.append(self.first_name)

        if self.mid_name:
            values.append(self.mid_name)

        if self.last_name:
            values.append(self.last_name)

        if values:
            return ' '.join(values)
        return ''


class City(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=100, blank=False, null=False, unique=True)
    map_url = models.URLField(blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        managed = True
        db_table = 'cities'

    def __str__(self):
        return self.name


class Search:
    queryset = None
    arguments = []
    local_search_arguments = []

    def __init__(self, queryset=None):
        if queryset:
            self.queryset = queryset

    def search(self, search_string):
        return self._search(self.arguments, search_string)

    def local_search(self, search_string):
        return self._search(self.local_search_arguments, search_string)

    def _search(self, arguments, search_string):
        listing = self.queryset

        for word in search_string.split():
            or_expression = Q()
            for argument in arguments:
                arg_dict = {argument: word}
                or_expression |= Q(**arg_dict)
            listing = listing.filter(or_expression)
        return listing


class CitySearch(Search):
    queryset = City.objects.all().order_by('name')
    arguments = [
        'name__icontains',
    ]


class Port(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=100, blank=False, null=False, unique=False)
    iface_index = models.IntegerField(null=True)
    # Don't forget to remove null and blank
    bundle = models.ForeignKey('common.Bundle', related_name='ports',
                               null=True, blank=True,
                               on_delete=models.CASCADE)
    description = models.CharField(max_length=100, blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def save(self, *args, **kwargs):
        self.iface_index = self._iface_index()
        super(Port, self).save(*args, *kwargs)

    def _iface_index(self):
        prefix = '100'

        if 'FastEthernet' in self.name:
            prefix = '110'

        if 'fe' in self.name:
            prefix = '110'

        if 'GigabitEthernet' in self.name:
            prefix = '120'

        if 'ge' in self.name:
            prefix = '120'

        if 'xe' in self.name:
            prefix = '140'

        if 'et' in self.name:
            prefix = '150'

        if 'ae' in self.name:
            prefix = '160'

        if 'po' in self.name:
            prefix = '160'

        name_normalized = self.name
        if '.' in self.name:
            parts = self.name.split('.')
            name_normalized = parts[0]
        iface_index = int(prefix + ''.join([x for x in list(name_normalized) if x.isdigit()]))
        return iface_index

    class Meta:
        managed = True
        db_table = 'ports'
        ordering = ['iface_index']
        unique_together = ('bundle', 'name')

    def __str__(self):
        return "%s (%s)" % (self.name, self.description)

    def is_updated_today(self):
        few_hours = datetime.timedelta(hours=12)
        return datetime.datetime.now() - self.updated < few_hours

    def is_gone(self):
        three_days = datetime.timedelta(days=3)
        return datetime.datetime.now() - self.updated > three_days

    def mrtg_name(self):
        return self.name


class BundleVlan(models.Model):
    MODES = (
        ("tagged", "Tagged"),
        ("untagged", "Untagged"),
    )
    services = models.ManyToManyField('common.Service', related_name='bundle_vlans')
    subservices = models.ManyToManyField('common.SubService', related_name='bundle_vlans')
    vlan = models.ForeignKey('vlans.Vlan', null=False, blank=False, on_delete=models.CASCADE)
    bundle = models.ForeignKey('common.Bundle', null=False, blank=False, on_delete=models.CASCADE)
    mode = models.CharField(max_length=20, blank=False, null=False, choices=MODES)
    comment = models.TextField(max_length=2048, blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = u'bundle_vlan'
        unique_together = ('bundle', 'vlan')

    def is_updated_today(self):
        few_hours = datetime.timedelta(hours=12)
        return datetime.datetime.now() - self.updated < few_hours

    def is_gone(self):
        three_days = datetime.timedelta(days=3)
        return datetime.datetime.now() - self.updated > three_days

    def __str__(self):
        return '%s:%s : %s [%s] %s' % (
            self.bundle.device.netname, self.bundle.name, self.vlan.vname, self.vlan.vlannum, self.mode[0].upper())


class Bundle(models.Model):
    name = models.CharField(max_length=50, null=False, blank=False)
    description = models.CharField(max_length=50, null=True, blank=True)
    iface_index = models.IntegerField(null=True)

    is_lag = models.BooleanField(default=False)
    device = models.ForeignKey('devices.Device', related_name='bundles',
                               null=False, blank=False,
                               on_delete=models.CASCADE)
    remote_device = models.ForeignKey('devices.Device', related_name='remote_bundles',
                                      null=True, blank=True,
                                      on_delete=models.SET_NULL)
    vlans = models.ManyToManyField('vlans.Vlan', related_name='bundles',

                                   through='common.BundleVlan')
    comment = models.TextField(max_length=2048, blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = 'bundles'
        ordering = ['iface_index']
        unique_together = ('device', 'name')

    def save(self, *args, **kwargs):
        self.iface_index = self._iface_index()
        super(Bundle, self).save(*args, *kwargs)

    def _iface_index(self):
        prefix = '100'

        if 'FastEthernet' in self.name:
            prefix = '110'

        if 'fe' in self.name:
            prefix = '110'

        if 'GigabitEthernet' in self.name:
            prefix = '120'

        if 'ge' in self.name:
            prefix = '120'

        if 'xe' in self.name:
            prefix = '140'

        if 'et' in self.name:
            prefix = '150'

        if 'ae' in self.name:
            prefix = '160'

        if 'po' in self.name:
            prefix = '160'

        name_normalized = self.name
        if '.' in self.name:
            parts = self.name.split('.')
            name_normalized = parts[0]

        iface_index = int(prefix + ''.join([x for x in list(name_normalized) if x.isdigit()]))

        return iface_index

    def mrtg_name(self):
        return self.name

    def traffic_ports(self):
        """
        Represents all ports to count traffic.
        If this is a Juniper ae* interface, will return the ae.
        Else will return it's members
        """
        if not self.device.store_entry:
            return []

hostel/common/templates/bs3/common/broadcrumbs_as.html
<ol class="breadcrumb">
    <li><a href="{% url 'clients' %}"><span class="glyphicon glyphicon-home" aria-hidden="true"></span></a></li>
    <li><a href="{% url 'client' asn.client.pk %}?tab=bgp">{{ asn.client }}</a></li>
    <li class="active">{{ asn }}</li>
</ol>

hostel/common/templates/bs3/common/broadcrumbs_service.html
<ol class="breadcrumb">
    <li><a href="{% url 'clients' %}"><span class="glyphicon glyphicon-home" aria-hidden="true"></span></a></li>
    <li><a href="{% url 'client' service.client.pk %}">{{ service.client }}</a></li>

    {% if service.asn %}
        <li><a href="{% url 'autonomous_system' service.asn.pk %}">{{ service.asn }}</a></li>
    {% endif %}
    <li class="active">{{ service }}</li>
</ol>

hostel/common/templates/bs3/common/broadcrumbs_subservice.html
<ol class="breadcrumb">
    <li><a href="{% url 'clients' %}"><span class="glyphicon glyphicon-home" aria-hidden="true"></span></a></li>
    <li><a href="{% url 'client' service.client.pk %}">{{ service.client }}</a></li>
    <li><a href="{% url 'service' service.pk %}?tab=subservices">{{ service }}</a></li>
    <li class="active">{{ subservice }}</li>
</ol>

hostel/common/templates/bs3/common/change_password_button.html
<div class="panel panel-default">
    <div class="panel-body text-right">
        <a class="btn btn-primary" data-toggle="modal" data-target="#create_password">Сменить пароль</a>
    </div>
</div>

<div class="modal fade" id="create_password" tabindex="-1" role="dialog">
    <form method="POST" action="{% url 'change-password' %}">
        {% csrf_token %}
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="myModalLabel">Смена пароля</h4>

                </div>

                <div class="modal-body">
                    <div class="form-group">
                        <label>Новый пароль</label>
                        <input class="form-control" type="password" name="password" placeholder="Пароль">
                        <input type="hidden" name="id" value="{{ manager.pk }}">
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Я еще подумаю...</button>
                    <input type="submit" class="btn btn-primary" value="Сменить пароль">
                </div>
            </div>
        </div>
    </form>
</div>

hostel/common/templates/bs3/common/created_updated.html
<div class="well well-sm text-muted">
    <small>

        <b>Создан:</b> {{ object.created|date:"Y-m-d в H:i" }}<br>
        <b>Обновлен:</b> {{ object.updated|date:"Y-m-d в H:i" }}<br>

        {% if object.creator %}
        <b>Создатель:</b> {{ object.creator }}<br>
        {% endif %}

        <b>ID:</b> {{ object.pk }}<br>

    </small>
</div>

hostel/common/templates/bs3/common/login.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>Hostel</title>

    <!-- jQuery -->
    <script src="https://code.jquery.com/jquery-3.2.1.min.js"
            integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=" crossorigin="anonymous"></script>


    <!-- jQuery UI -->
    <link rel="stylesheet" href="http://code.jquery.com/ui/1.8.18/themes/base/jquery-ui.css" type="text/css"
          media="all"/>
    <script src="http://code.jquery.com/ui/1.12.1/jquery-ui.min.js" type="text/javascript"></script>


    <!-- Bootstrap -->
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">

    <!-- Optional theme -->
    <!-- link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous" -->

    <!-- jQuery -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->


    <style>
    body { padding-top: 90px;}
    </style>

</head>
<body>



<div class="container">


<div class="container">
    <nav class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <div class="navbar-header">
         <a class="navbar-brand"><span class="hidden-sm hidden-xs" style="color: #cccccc;"><b>Hostel</b></span></a>
        </div>



      </div>
    </nav>

    {% include 'bs3/messages.html' %}

<style>
body {
  padding-bottom: 40px;
  background-color: #eee;
}

.form-signin {
  max-width: 330px;
  padding: 15px;
  margin: 0 auto;
}
.form-signin .form-signin-heading,
.form-signin .checkbox {
  margin-bottom: 10px;
}
.form-signin .checkbox {
  font-weight: normal;
}
.form-signin .form-control {
  position: relative;
  height: auto;
  -webkit-box-sizing: border-box;
     -moz-box-sizing: border-box;
          box-sizing: border-box;
  padding: 10px;
  font-size: 16px;
}
.form-signin .form-control:focus {
  z-index: 2;
}
.form-signin input[type="text"] {
  margin-bottom: -1px;
  border-bottom-right-radius: 0;
  border-bottom-left-radius: 0;
}
.form-signin input[type="password"] {
  margin-bottom: 10px;
  border-top-left-radius: 0;
  border-top-right-radius: 0;
}

</style>

<div class="container"></div>
     <div class="container">

      <form class="form-signin" action="?page=login&next={{ next }}" method="POST">
        {% csrf_token %}
        <input type="hidden" name="next" value="{{ next }}">
        <h2 class="form-signin-heading">Вход в систему</h2>
        <label for="login" class="sr-only">Имя пользователя</label>
        <input type="text" id="login" name="login" class="form-control" placeholder="Логин" value="{{ login }}" required autofocus>
        <label for="password" class="sr-only">Пароль</label>
        <input type="password" id="password" name="password" class="form-control" placeholder="Пароль" required>
        <button class="btn btn-lg btn-primary btn-block" type="submit">Войти</button>
      </form>

    </div> <!-- /container -->

</div>

hostel/common/templates/bs3/common/service_bgpinet.html
{% extends 'bs3/base.html' %}

{% block content %}

<ul class="nav nav-tabs">
    <li role="presentation"><a href="index.php?page=services#service_{{ service.pk }}">Клиенты</a></li>
</ul>

<div class="container">


    <!-- Заголовок странички, кнопка редактирования -->
    <h2>Услуга
        <small>{{ service.name }}</small>

        {% if mode == 'edit' %}
        <a class="btn btn-default"
           href="index.php?page=service&action=view&id={{ service.pk }}&client_id={{ client.pk }}">Отмена</a>
        <button type="submit" form="serviceData" class="btn btn-danger">Сохранить</button>
        {% else %}
        <a class="btn btn-default"
           href="?page=service&action=view&mode=edit&id={{ service.pk }}&client_id={{ client.pk }}">Редактировать</a>
        {% endif %}

    </h2>

    <!-- Колонка с общими данными клиента -->
    <div class="row">
        <div class="col-md-4">
        </div>

        <div class="col-md-4">


            <!-- Данные услуги -->
            <label>#RT</label>
                {% if form.rt.errors %}
                {{ form.rt.errors }}
                {% endif %}
            <div>{{ form.rt }}</div>

            <label>Тип</label>
                {% if form.servicetype.errors %}
                {{ form.servicetype.errors }}
                {% endif %}
            <div>{{ form.servicetype }}</div>

            <label>AS</label>
                {% if form.autonomoussystem.errors %}
                {{ form.autonomoussystem.errors }}
                {% endif %}
            <div>{{ form.autonomoussystem }}</div>

            <label>Vlan</label>
                {% if form.vlan.errors %}
                {{ form.vlan.errors }}
                {% endif %}
            <div>{{ form.vlan }}</div>

            <label></label>
                {% if form..errors %}
                {{ form..errors }}
                {% endif %}
            <div>{{ form. }}</div>

            <label>Статус</label>
                {% if form.status.errors %}
                {{ form.status.errors }}
                {% endif %}
            <div>{{ form.status }}</div>


        </div>

        <!-- Колонка с услугами -->
        <div class="col-md-4">
        </div>
    </div>


</div>

{% endblock %}

hostel/common/templates/bs3/common/view_user_profile.html
{% extends 'bs3/base.html' %}

{% block content %}

    {% load static %}

    <div class="container">
        <div class="page-header text-right">
            <h2><span class="pull-left">Настройки профиля</span>
                <input type="submit" form="user_form" class="btn btn-primary" value="Сохранить">
            </h2>
        </div>

        <form id="user_form" METHOD="POST" enctype="multipart/form-data">
            {% csrf_token %}

            <div class="row">


                <div class="col-md-4 text-center">

                    <h3>Фото</h3>

                    {% if user.photo %}
                        <img class="img-thumbnail" src="{{ user.photo.url }}" style="width: 50%">
                    {% else %}
                        <img class="img-circle" src="{% static '/i/' %}no-photo.png" style="width: 50%">
                    {% endif %}

                    <div class="form-group {% if form.photo.errors %}has-error{% endif %}">
                        <label class="control-label">Загрузить</label>
                        {% for error in form.photo.errors %}
                            <span class="error">{{ error }}</span>
                        {% endfor %}<br>
                        {{ form.photo }}
                    </div>

                </div>

                <div class="col-md-4">

                    <h3>Персональные данные</h3>

                    <div class="form-group {% if form.username.errors %}has-error{% endif %}">
                        <label class="control-label">Логин</label><br>
                        {{ form.username }}
                        {% for error in form.username.errors %}
                            <p class="error">{{ error }}</p>
                        {% endfor %}
                    </div>

                    <div class="form-group {% if form.first_name.errors %}has-error{% endif %}">
                        <label class="control-label">Имя</label>
                        {% for error in form.first_name.errors %}
                            <span class="error">{{ error }}</span>
                        {% endfor %}<br>
                        {{ form.first_name }}
                    </div>
                    <div class="form-group {% if form.last_name.errors %}has-error{% endif %}">
                        <label class="control-label">Фамилия</label>
                        {% for error in form.last_name.errors %}
                            <span class="error">{{ error }}</span>
                        {% endfor %}<br>
                        {{ form.last_name }}
                    </div>
                    <div class="form-group {% if form.mid_name.errors %}has-error{% endif %}">
                        <label class="control-label">Отчество</label>
                        {% for error in form.mid_name.errors %}
                            <span class="error">{{ error }}</span>
                        {% endfor %}<br>
                        {{ form.mid_name }}
                    </div>

                    <div class="form-group {% if form.email.errors %}has-error{% endif %}">
                        <label class="control-label">Email</label>
                        {% for error in form.email.errors %}
                            <span class="error">{{ error }}</span>
                        {% endfor %}<br>
                        {{ form.email }}
                    </div>
                    <div class="form-group {% if form.phone.errors %}has-error{% endif %}">
                        <label class="control-label">Телефон</label>
                        {% for error in form.phone.errors %}
                            <span class="error">{{ error }}</span>
                        {% endfor %}<br>
                        {{ form.phone }}
                    </div>
                    <div class="form-group {% if form.ext_phone.errors %}has-error{% endif %}">
                        <label class="control-label">Добавочный телефон</label>
                        {% for error in form.ext_phone.errors %}
                            <span class="error">{{ error }}</span>
                        {% endfor %}<br>
                        {{ form.ext_phone }}
                    </div>
                    <div class="form-group {% if form.birthday.errors %}has-error{% endif %}">
                        <label class="control-label">ДР 🎂</label>
                        {% for error in form.birthday.errors %}
                            <span class="error">{{ error }}</span>
                        {% endfor %}<br>
                        {{ form.birthday }}
                    </div>
                    <div class="form-group {% if form.genter.errors %}has-error{% endif %}">
                        <label class="control-label">Пол</label>
                        {% for error in form.gender.errors %}
                            <span class="error">{{ error }}</span>
                        {% endfor %}<br>
                        {{ form.gender }}
                    </div>
                    <script>
                        $(function () {
                            $("#id_birthday").datepicker({
                                "dateFormat": "yy-mm-dd",
                                changeMonth: true,
                                changeYear: true,
                                yearRange: "1940:2000"
                            });
                        });
                    </script>

                    <div class="form-group {% if form.position.errors %}has-error{% endif %}">
                        <label class="control-label">Должность</label>
                        {% for error in form.position.errors %}
                            <span class="error">{{ error }}</span>
                        {% endfor %}<br>
                        {{ form.position }}
                    </div>

                </div>

                <div class="col-md-4">

                    <h3>Настройки Hostel</h3>

                    <div class="form-group {% if form.kind.errors %}has-error{% endif %}">
                        <label class="control-label">Тип профиля</label>
                        {% for error in form.kind.errors %}
                            <span class="error">{{ error }}</span>
                        {% endfor %}<br>
                        {{ form.kind }}
                    </div>
                    <div class="form-group {% if form.theme.errors %}has-error{% endif %}">
                        <label class="control-label">Внешний вид Хостела</label>
                        {% for error in form.theme.errors %}
                            <span class="error">{{ error }}</span>
                        {% endfor %}<br>
                        {{ form.theme }}
                    </div>
                    <div class="form-group {% if form.pagination_count.errors %}has-error{% endif %}">
                        <label class="control-label">Объектов на страницу</label>
                        {% for error in form.pagination_count.errors %}
                            <span class="error">{{ error }}</span>
                        {% endfor %}<br>
                        {{ form.pagination_count }}
                    </div>

                </div>
            </div>

        </form>


        {% if mode == "view" %}
            {% include 'bs3/common/change_password_button.html' %}
        {% endif %}
    </div>
    <!-- Правая колонка -->
    <div class="col-md-4">
    </div>
    </div>
    </div>

{% endblock %}